### ISSUE TITLE
Random walk simulation

### ISSUE THREAD

**Issue by jacobtnyoung** [DS4PS/ms-prog-eval-data-analytics#11]
Hi David (or anyone),

For the simulation example, I have a question about this question:

"Run 100 simulations to measure time, each with 100 loops over the game to measure run times. Report your results."

Does this mean to run the simulation given 100 times? So, that we would have 100 different system run times? Thanks!

**Comment by lecy** [comment]
Did you figure it out? 

They will write a function to play the game (call all steps in order). The simulation would just be a loop to play the game 100 times and store results from each. 

Run time would be total time for all loops: 

```r
start.time <- time()

loops

end.time <- time()

run.time <- end.time - start.time
```

**Comment by jacobtnyoung** [comment]
I closed it because I can't remember whether I did it or not. 😂
